### ISSUE TITLE
O arquivo TOTVS.CH está sem conteudo

### ISSUE THREAD

**Issue by edusfc15** [imsys/Protheus-Include#1]
Boa tarde,

o arquivo: 
https://github.com/imsys/Protheus-Include/blob/master/include/totvs.ch

está quase vazio e creio que não seja o seu conteúdo correto.

Se puder, por favor verificar. 

Grato.

**Comment by vitorebatista** [comment]
O `Totvs.ch` é apenas um _alias_ pro `Protheus.ch`, dá na mesma chamar um ou o outro.

**Comment by edusfc15** [comment]
Ok, grato pelo esclarecimento.
